### ISSUE TITLE
RSS Cog is hanging.

### ISSUE THREAD

**Issue by Injabie3** [Injabie3/lui-cogs#4]
Occasionally, the RSS cog hangs and does not update.  Reloading fixes the issue.

![screenshot](https://puu.sh/uHLW9/10bf0ba999.jpg)

**Comment by Injabie3** [comment]
![Another hang](https://puu.sh/uIMhj/43ec816eba.jpg)

**Comment by Injabie3** [comment]
![screenshot](https://puu.sh/vkwnr/99d0c0a66e.jpg)

**Comment by Injabie3** [comment]
Probably need an exception handler for this.

**Comment by abuneri** [comment]
only using urllib temporarily, will be switch to aiohttp soon(tm)

**Comment by Injabie3** [comment]
We also need to handle the explicit filter and the exception:
```
RSS: no new items in feed 0
RSS: 1 new items in feed 1
------------------------------------
RSS: scanning feed(s) for updates...
------------------------------------
RSS: 2 new items in feed 0
RSS: 1 new items in feed 1
------------------------------------
RSS: scanning feed(s) for updates...
------------------------------------
RSS: 2 new items in feed 0
RSS: 1 new items in feed 1
------------------------------------
RSS: scanning feed(s) for updates...
------------------------------------
RSS: 2 new items in feed 0
RSS: 1 new items in feed 1
Task exception was never retrieved
future: <Task finished coro=<RSSFeed._rss() done, defined at /home/ubuntu/github/Ren/cogs/rss.py:150> exception=HTTPException('BAD REQUEST (status code: 400): Explicit content cannot be sent to the desired recipient(s)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ubuntu/github/Ren/cogs/rss.py", line 199, in _rss
    await self.bot.send_message(post_channel, embed=embed)
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Explicit content cannot be sent to the desired recipient(s)
------------------------------------
RSS: scanning feed(s) for updates...
------------------------------------
RSS: 29 new items in feed 0
RSS: 23 new items in feed 1
```

**Comment by Injabie3** [comment]
Explicit filter again, doesn't seem to happen too often.  At least I know if it doesn't work due to the heartbeat.
```
RSS: 1 new items in feed 0
RSS: 1 new items in feed 1
------------------------------------
RSS: scanning feed(s) for updates...
------------------------------------
RSS: 1 new items in feed 0
RSS: 1 new items in feed 1
Task exception was never retrieved
future: <Task finished coro=<RSSFeed._rss() done, defined at /home/ubuntu/github/Ren/cogs/rss.py:150> exception=HTTPException('BAD REQUEST (status code: 400): Explicit content cannot be sent to the desired recipient(s)',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ubuntu/github/Ren/cogs/rss.py", line 199, in _rss
    await self.bot.send_message(post_channel, embed=embed)
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Explicit content cannot be sent to the desired recipient(s)
------------------------------------
RSS: scanning feed(s) for updates...
------------------------------------
RSS: 4 new items in feed 0
RSS: 3 new items in feed 1
```

**Comment by Injabie3** [comment]
Explicit filter case handled, also saw this error today:
```
ime":130,"atts":"GBFTEQoaHE4=","errorBeacon":"bam.nr-data.net","agent":""}</script></body>\n  <!--  pylon19 : 82ded3afdc-release-2017-08-07 -->\n</html>\n', 22884, 22885, 'invalid start byte')>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ubuntu/github/Ren/cogs/rss.py", line 182, in _rss
    page = await resp.text()
  File "lib/aiohttp/client_reqrep.py", line 769, in text
    return self._content.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 22884: invalid start byte
------------------------------------
```

**Comment by Injabie3** [comment]
Closing, issue too vague right now.

Recent refactoring in 3e36885c607f4e5cc4b36ac4fa9bbc10c98de861...85171ffd8aae4e28aa1a5015413d27887752193e and ca0a9fd76de156ea0cb76a2eb8d1c1c5ea4807c4...dd6f93e79a54bd065d4596f7d5cc37f0e2d5f9da have addressed the RSS hanging issue.
